name: ci.yml

on:
  pull_request:
    push:
      workflow_dispatch:

jobs:
  Terrascan:
    name: Terrascan Scan
    runs-on: ubuntu-latest
    container:
      image: naveen2131/my-app:baseimage
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Helm Template and Scanning
        run: |
          helm template charts/k8tz/ --output-dir "./charts/output"
          terrascan scan -i k8s
